// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALHgjRrATwlELbYl5N_9eBzUnLyhP0WsQ',
    appId: '1:647893167745:web:3b4c369f2f212eb6456780',
    messagingSenderId: '647893167745',
    projectId: 'comments-da8f7',
    authDomain: 'comments-da8f7.firebaseapp.com',
    databaseURL: 'https://comments-da8f7-default-rtdb.firebaseio.com',
    storageBucket: 'comments-da8f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuT6Ix7-DCR-UZ_bXheZZ_sYaG3A6zM2o',
    appId: '1:647893167745:android:7bcb777e1323f0de456780',
    messagingSenderId: '647893167745',
    projectId: 'comments-da8f7',
    databaseURL: 'https://comments-da8f7-default-rtdb.firebaseio.com',
    storageBucket: 'comments-da8f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8w8MEw0GPHrdyfGXMiRWZWtCkVvHGMU',
    appId: '1:647893167745:ios:849becddfd14d3ba456780',
    messagingSenderId: '647893167745',
    projectId: 'comments-da8f7',
    databaseURL: 'https://comments-da8f7-default-rtdb.firebaseio.com',
    storageBucket: 'comments-da8f7.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8w8MEw0GPHrdyfGXMiRWZWtCkVvHGMU',
    appId: '1:647893167745:ios:849becddfd14d3ba456780',
    messagingSenderId: '647893167745',
    projectId: 'comments-da8f7',
    databaseURL: 'https://comments-da8f7-default-rtdb.firebaseio.com',
    storageBucket: 'comments-da8f7.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALHgjRrATwlELbYl5N_9eBzUnLyhP0WsQ',
    appId: '1:647893167745:web:decbc8637c71dcfb456780',
    messagingSenderId: '647893167745',
    projectId: 'comments-da8f7',
    authDomain: 'comments-da8f7.firebaseapp.com',
    databaseURL: 'https://comments-da8f7-default-rtdb.firebaseio.com',
    storageBucket: 'comments-da8f7.appspot.com',
  );
}
